"""Initial Migration

Revision ID: b9618f6fb95f
Revises: f1a90e784faa
Create Date: 2020-01-19 12:25:29.005897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9618f6fb95f'
down_revision = 'f1a90e784faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_password_hash_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_hash_key', 'users', ['password_hash'])
    # ### end Alembic commands ###
